_wandb:
    value:
        cli_version: 0.25.1
        e:
            uyr3u1irmkxbj5s3jkmywizu8jjf05a3:
                args:
                    - --dataset-type
                    - scanobjectnn
                    - --use-wandb
                    - --wandb-project
                    - TSDF-PointNet
                    - --wandb-run-name
                    - scanobjectnn_pb_t50_rs
                codePath: detection/train_pointnet_cls.py
                codePathLocal: detection/train_pointnet_cls.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "487863541760"
                        used: "444132749312"
                email: fhc1572997072@gmail.com
                executable: /home/yuhang/miniconda3/envs/tsdf/bin/python
                git:
                    commit: a1619a043b454c9015c981d47de5ed9ad3034c6a
                    remote: git@github-haochen:HaochenFeng0101/TSDF.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-56838aa4-511f-eff4-5578-5f13383dbd32
                host: yuhang.han-laptop
                memory:
                    total: "32868933632"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /media/yuhang/Data1/TSDF/detection/train_pointnet_cls.py
                python: CPython 3.10.20
                root: /media/yuhang/Data1/TSDF
                startedAt: "2026-03-17T05:57:27.890725Z"
                writerId: uyr3u1irmkxbj5s3jkmywizu8jjf05a3
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.10.20
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 32
data_root:
    value: null
dataset_type:
    value: scanobjectnn
device:
    value: cuda
dropout:
    value: 0.4
epochs:
    value: 100
feature_transform_weight:
    value: 0.001
label_smoothing:
    value: 0.1
labels:
    value: null
labels_path:
    value: /media/yuhang/Data1/TSDF/model/pointnet/labels.txt
lr:
    value: 0.001
num_classes:
    value: 15
num_points:
    value: 1024
output_dir:
    value: /media/yuhang/Data1/TSDF/model/pointnet
scanobjectnn_no_bg:
    value: false
scanobjectnn_root:
    value: /media/yuhang/Data1/TSDF/data/ScanObjectNN
scanobjectnn_variant:
    value: pb_t50_rs
seed:
    value: 0
test_h5:
    value: null
train_h5:
    value: null
use_class_weights:
    value: false
use_wandb:
    value: true
wandb_project:
    value: TSDF-PointNet
wandb_run_name:
    value: scanobjectnn_pb_t50_rs
weight_decay:
    value: 0.0001
workers:
    value: 4
