Dataset:
  type: "tum"
  sensor_type: "depth"
  pcd_downsample: 128
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01

Results:
  save_results: True
  save_dir: "3d_construction/outputs"
